# Generated by Django 3.1.4 on 2020-12-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.food')),
                ('salad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salad_type')),
            ],
            bases=('orders.food',),
        ),
        migrations.CreateModel(
            name='Regular_Pizza',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.food')),
                ('number_toppings', models.IntegerField()),
                ('topping_types', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.food',),
        ),
        migrations.CreateModel(
            name='Dinner_platter',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.food')),
                ('platter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salad_type')),
            ],
            bases=('orders.food',),
        ),
    ]
