# Generated by Django 3.1.4 on 2020-12-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinner_platter_regular_pizza_salad_salad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platter',
            name='platter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.platter_type'),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.food')),
                ('pasta_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pasta_type')),
            ],
            bases=('orders.food',),
        ),
    ]
