# Generated by Django 3.1.4 on 2020-12-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201225_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
    ]
