# Generated by Django 3.1.4 on 2020-12-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_food_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
    ]
